travis:
  secure:
    BINSTAR_TOKEN: ZGpotFJjrk17PzC2tqnAi8d1UrSS1/8ohhMlFhkxgfZ/Oyu12YzsgdyWGbh/q+1TH7KTyOWDOIuNAvBzV+lF4s5aAUTKIUwt2NWwAYYENiIW78pSnkED161r7EFdO4tcLx0JKF7ewUF3E2QY//Sbe1Tl/R7mS8SV6/S94LAeVAziciW829EvE/3/LotUoaJYMka42CbFhrkHj1cET0trC/OHl2jBm/N1hED9pKXIavd9zvE4gzHMnNktAxT3eFQbaa4O62AhczZPuwAQ7NDzq/4C1J5bU+xdVV7dRLmXv3nB+XvUzK3QIWqi2YL5z6skj8Lmdq+wTAZ5lRdyL52X80H2T14Vgqpy8TDqxoqHYdDzZj+QxoGJ4x6faWXrrrzV+47/QZbwBGNryV4ztAfceg0MbiRVxPzNomMTWJz90OwnmXZzBD4rC+TYl3BERVHvmzrh0jtxPutAK1IvJjrU7zS4dGLs1RnnA0CkEANOYRD3r+enKMmo3bWtictRvJCBowqli29gI1fFSltvM9w+WLQ7LG1r6uROdfn6KJUZ9HOMvHEwd2zJBusAVkNICGA8Olll51CUfcH3mQmP8TehLUc98oq8ZKzaOyGL13h1yzbd3CTjz8tNKvFAsa1GxZBeC7Oii21refcS0fRPb0z5eGQvAnOOIevm/LIrnVLXir0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
